### ✅ 목표 설정
- 선형 회귀의 사용법 알아보기
- 학습된 선형 회귀 모델의 가중치와 편향 확인해보기
- -> 어떤 모델을 사용할 것인가? : 선형 회귀
- -> 어떤 데이터를 이용할 것인가? : numpy로 만든 단순한 수치 데이터

In [1]:
# 필요한 라이브러리 가져오기

import numpy as np

In [2]:
X = np.arange(1, 10, 2)
X

array([1, 3, 5, 7, 9])

In [3]:
y = np.arange(10, 100, 20)
y

array([10, 30, 50, 70, 90])

### ✅ 필요한 모델 불러오기
- 선형 회귀 모델

In [4]:
# 사이킷런에 선형 모델 모음집에서 선형 회귀 모델을 import 할거야!

from sklearn.linear_model import LinearRegression

In [5]:
# 모델 객체 생성

linear = LinearRegression()

In [7]:
# X 데이터를 2차원으로 바꿔주자

X_ = X.reshape(5, 1) # 5행, 1열
X_

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [9]:
# 모델 학습
# 선형 회귀를 사용할 때 특성 데이터는 2차원의 형태를 가지고 있어야 한다. (주의사항)

linear.fit(X_, y)

LinearRegression()

In [11]:
# 선형 회귀 모델 예측

pre = linear.predict([[6]]) # 2차원으로 만들어주기 위해 [] 더 감싸줌
pre

array([60.])

In [12]:
# 학습된 선형 회귀 모델의 가중치를 확인하는 명령어 -> 가중치 개수 = x 의 개수

linear.coef_ # y = 10x + 0 의 10

array([10.])

In [14]:
# 학습된 선형 회귀 모델의 편향을 확인하는 명령어

int(linear.intercept_) # y = 10x + 0 의 0

0